### ISSUE TITLE
Don't step on Halium

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-boot#4]
A Halium build tree should, in theory, be able to make Halium images even though ubports-boot is present. This is not currently possible in the current implementation.

These are the issues that must be fixed to coexist in a Halium tree:

- [ ]  #1 Block device nodes with friendly names should be in `/dev/block` rather than `/dev` itself
- [ ]  #2 Write a better way to embed the /data partition
- [x]  #3 hybris-boot won't boot when ubports-boot is in the source tree

This issue should be closed when it is possible to build working ubports-boot and hybris-boot images from the same Halium source tree without modifying any device sources.
